package com.cobre.notification.adapter.in.kafka;

/**
 * A platform event that can never be processed (malformed or violating the schema). Not retried.
 * The message is generated by this service and never contains the event payload.
 */
public class InvalidPlatformEventException extends RuntimeException {

    private final String reason;

    public InvalidPlatformEventException(String reason) {
        super("Invalid platform event: " + reason);
        this.reason = reason;
    }

    public String reason() {
        return reason;
    }
}
