package com.cobre.notification.domain.model;

import java.util.Objects;

/**
 * Error details that are safe to persist and expose: a stable code plus a message generated by this service.
 * Never built from webhook response bodies or event content.
 */
public record DeliveryError(String code, String message) {

    public static final int MAX_MESSAGE_LENGTH = 500;
    public static final int MAX_CODE_LENGTH = 50;

    public DeliveryError {
        Objects.requireNonNull(code, "code");
        code = truncate(stripControlCharacters(code), MAX_CODE_LENGTH);
        message = message == null ? null : truncate(stripControlCharacters(message), MAX_MESSAGE_LENGTH);
    }

    public static DeliveryError httpStatus(int statusCode) {
        return new DeliveryError("http_status", "HTTP " + statusCode);
    }

    public String summary() {
        return truncate(message == null ? code : code + ": " + message, MAX_MESSAGE_LENGTH);
    }

    private static String stripControlCharacters(String value) {
        return value.replaceAll("\\p{Cntrl}", " ");
    }

    private static String truncate(String value, int maxLength) {
        return value.length() <= maxLength ? value : value.substring(0, maxLength);
    }
}
