package com.cobre.notification.domain.model;

import java.util.Objects;

/**
 * Error details that are safe to persist and expose: a stable code plus a message generated by this service.
 * Never built from webhook response bodies or event content.
 */
public record DeliveryError(String code, String message) {

    public static final int MAX_MESSAGE_LENGTH = 500;
    public static final int MAX_CODE_LENGTH = 50;

    public static final String HTTP_STATUS = "http_status";
    public static final String INVALID_DESTINATION = "invalid_destination";
    public static final String LEASE_EXPIRED = "lease_expired";
    public static final String FIXTURE_SYNTHETIC = "fixture_synthetic";

    public DeliveryError {
        Objects.requireNonNull(code, "code");
        code = truncate(stripControlCharacters(code), MAX_CODE_LENGTH);
        message = message == null ? null : truncate(stripControlCharacters(message), MAX_MESSAGE_LENGTH);
    }

    public static DeliveryError httpStatus(int statusCode) {
        return new DeliveryError(HTTP_STATUS, "HTTP " + statusCode);
    }

    public static DeliveryError leaseExpired() {
        return new DeliveryError(LEASE_EXPIRED, "Worker lease expired before the result was recorded");
    }

    /**
     * Same code, with the reason the notification stopped being retried.
     */
    public DeliveryError retriesExhausted(int attempts) {
        String exhausted = "retries exhausted after " + attempts + " attempts";
        return new DeliveryError(code, message == null ? exhausted : message + "; " + exhausted);
    }

    public String summary() {
        return truncate(message == null ? code : code + ": " + message, MAX_MESSAGE_LENGTH);
    }

    private static String stripControlCharacters(String value) {
        return value.replaceAll("\\p{Cntrl}", " ");
    }

    private static String truncate(String value, int maxLength) {
        return value.length() <= maxLength ? value : value.substring(0, maxLength);
    }
}
